version = 1

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/Henry-XiaoH/dashboard"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["angular"]